### ISSUE TITLE
启动不了，报错java.lang.NoClassDefFoundError: io.rong.imlib.RongIMClient

### ISSUE THREAD

**Issue by shufanshijie** [rongcloud/demo-imlib-android#1]
clone下来后，在模拟器和真机上运行都会报错，请检查
02-03 01:27:12.882: E/AndroidRuntime(940): FATAL EXCEPTION: main
02-03 01:27:12.882: E/AndroidRuntime(940): java.lang.NoClassDefFoundError: io.rong.imlib.RongIMClient
02-03 01:27:12.882: E/AndroidRuntime(940): 	at io.rong.imlib.demo.App.onCreate(App.java:23)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.os.Looper.loop(Looper.java:137)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at java.lang.reflect.Method.invoke(Method.java:525)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-03 01:27:12.882: E/AndroidRuntime(940): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by DragonJ-GAO** [comment]
我们在技术群里面出现过类似的状况。可以检查一下你的Android SDK Tools版本23+测试是解决了问题的。建议升级至最新SDK
